#! /bin/sh
set -e

if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 0.4-1; then
    dpkg-divert --add --rename \
                --divert /etc/huayra/grub/windows.tmpl.deprecated \
                /etc/huayra/grub/windows.tmpl

    dpkg-divert --add --rename \
                --divert /etc/huayra/grub/recuperacion.tmpl.deprecated \
                /etc/huayra/grub/recuperacion.tmpl

    dpkg-divert --add --rename \
                --divert /usr/share/huayra-partition-tools/31_partition-finder.deprecated \
                /etc/grub.d/31_partition-finder

    cp /usr/share/huayra-partition-tools/tmpl/windows.tmpl \
       /etc/huayra/grub/windows.tmpl

    cp /usr/share/huayra-partition-tools/tmpl/recuperacion.tmpl \
       /etc/huayra/grub/recuperacion.tmpl

    cp /usr/share/huayra-partition-tools/partition-finder.py \
       /etc/grub.d/31_partition-finder

    chmod +x /etc/grub.d/31_partition-finder
fi

if [ "$1" = "configure" ];
then

    # actualizamos al grub con las nuevas configs.
    if test -e /boot/grub/grub.cfg && [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ];
    then
        update-grub
    fi

fi

#DEBHELPER#
